### ISSUE TITLE
mongodb orm 

### ISSUE THREAD

**Issue by jilgue** [CallePuzzle/donde-esta-tu-local#3]
https://mongoosejs.com/docs/index.html

https://github.com/gustavocadev/mongoose-sveltekit-example/blob/b927c6d2b7672eb83e6f3e9286d47087ca16f842/src/hooks.server.ts

**Comment by jilgue** [comment]
mongoosejs no funciona con cloudflare workers:

```
  "exceptions": [
    {
      "stack": "    at GetConnectedMongoose (worker.js:27636:33)\n    at .svelte-kit/output/server/chunks/auth.js (worker.js:27666:22)\n    at __init (worker.js:10:56)\n    at .svelte-kit/output/server/chunks/hooks.server.js (worker.js:27701:11)\n    at __init (worker.js:10:56)\n    at get_hooks (worker.js:30019:14)\n    at Server.init (worker.js:32862:30)\n    at Object.fetch (worker.js:32958:18)",
      "name": "TypeError",
      "message": "import_mongoose.default.connect is not a function",
      "timestamp": 1722065123881
    }
  ],
```

Según la [documentación](https://developers.cloudflare.com/workers/databases/connecting-to-databases/) para conectar con mongodb hay que usar [realm-web](https://www.mongodb.com/docs/realm/web/)

**Comment by jilgue** [comment]
Cloudflare tiene su propia base de datos [D1](https://developers.cloudflare.com/d1/), una especie de sqlite, con [free tier](https://developers.cloudflare.com/d1/platform/pricing/) parecido a mongodb.

Funciona con sveltekit: https://developers.cloudflare.com/d1/examples/d1-and-sveltekit/

Lucia-auth permite usar D1: https://lucia-auth.com/database/sqlite

**Comment by jilgue** [comment]
Pegamos el código que hemos usado por tenerlo de referencia y cerramos issue.

```js
import { MONGO_URI } from '$env/static/private';
import mongoose from 'mongoose';
import { logger } from '$lib/server/logger';

export async function GetConnectedMongoose(): Promise<typeof mongoose> {
	await mongoose.connect(MONGO_URI);
	mongoose.set('debug', (collectionName, method, query, doc) => {
		logger.debug({ query: query, doc: doc }, `${collectionName}.${method}`);
	});
	return mongoose;
}
```

```js
import { GetConnectedMongoose } from '$lib/mongoose';

const mongoose = await GetConnectedMongoose();

export const User = mongoose.model(
	'User',
	new mongoose.Schema(
		{
			_id: {
				type: String,
				required: true
			},
			email: {
				type: String,
				required: true
			}
		} as const,
		{ _id: false }
	)
);
```

```js
                const tokens = await auth0.validateAuthorizationCode(code);
		const response = await fetch(Auth0AppDomain + '/userinfo', {
			headers: {
				Authorization: `Bearer ${tokens.accessToken}`
			}
		});
		const user = await response.json();
		logger.info(user, 'user info from auth0');
		const existingUser = await User.findById(user.sub).exec();
		logger.debug(existingUser, 'existing user');
		if (existingUser) {
			const session = await lucia.createSession(existingUser.id, {});
			const sessionCookie = lucia.createSessionCookie(session.id);
			event.cookies.set(sessionCookie.name, sessionCookie.value, {
				path: '.',
				...sessionCookie.attributes
			});
		} else {
			const userId = generateId(15);
			await User.create({
				_id: user.sub,
				email: user.email
			});
			const session = await lucia.createSession(userId, {});
			const sessionCookie = lucia.createSessionCookie(session.id);
			event.cookies.set(sessionCookie.name, sessionCookie.value, {
				path: '.',
				...sessionCookie.attributes
			});
		}
		return new Response(null, {
			status: 302,
			headers: {
				Location: '/'
			}
		});
```
